language: node_js
node_js:
- 'stable'
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
services:
- postgresql
before_script:
- psql -c 'create database web_chat_test;' -U postgres
before_install:
- npm update
install:
- npm install
script:
- npm run coveralls